<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ChiTietSanPhamTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $list=[
            [
                'sp_id'                 => '1',
                'ha_id'                 => '1',        
                'm_id'                  => '1',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '1',
                'ha_id'                 => '2',        
                'm_id'                  => '2',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '5',        
            ],
            [
                'sp_id'                 => '1',
                'ha_id'                 => '1',        
                'm_id'                  => '1',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '1',        
            ],
            [
                'sp_id'                 => '1',
                'ha_id'                 => '2',        
                'm_id'                  => '2',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '1',
                'ha_id'                 => '1',        
                'm_id'                  => '1',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '1',
                'ha_id'                 => '2',        
                'm_id'                  => '2',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '5',        
            ],
            [
                'sp_id'                 => '2',
                'ha_id'                 => '3',        
                'm_id'                  => '1',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '3',        
            ],
            [
                'sp_id'                 => '2',
                'ha_id'                 => '3',        
                'm_id'                  => '1',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '9',        
            ],
            [
                'sp_id'                 => '2',
                'ha_id'                 => '3',        
                'm_id'                  => '1',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '2',
                'ha_id'                 => '4',        
                'm_id'                  => '5',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '12',        
            ],
            [
                'sp_id'                 => '2',
                'ha_id'                 => '4',        
                'm_id'                  => '5',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '20',        
            ],
            [
                'sp_id'                 => '2',
                'ha_id'                 => '4',        
                'm_id'                  => '5',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '2',
                'ha_id'                 => '5',        
                'm_id'                  => '3',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '5',        
            ],
            [
                'sp_id'                 => '2',
                'ha_id'                 => '5',        
                'm_id'                  => '3',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '2',
                'ha_id'                 => '5',        
                'm_id'                  => '3',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '3',
                'ha_id'                 => '6',        
                'm_id'                  => '1',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '3',
                'ha_id'                 => '6',        
                'm_id'                  => '1',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '3',
                'ha_id'                 => '6',        
                'm_id'                  => '1',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '3',
                'ha_id'                 => '7',        
                'm_id'                  => '2',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '3',
                'ha_id'                 => '7',        
                'm_id'                  => '2',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '3',
                'ha_id'                 => '7',        
                'm_id'                  => '2',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '3',
                'ha_id'                 => '8',        
                'm_id'                  => '3',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '3',
                'ha_id'                 => '8',        
                'm_id'                  => '3',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '3',
                'ha_id'                 => '8',        
                'm_id'                  => '3',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '4',
                'ha_id'                 => '9',        
                'm_id'                  => '1',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '4',
                'ha_id'                 => '9',        
                'm_id'                  => '1',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '4',
                'ha_id'                 => '9',        
                'm_id'                  => '1',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '4',
                'ha_id'                 => '10',        
                'm_id'                  => '2',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '4',
                'ha_id'                 => '10',        
                'm_id'                  => '2',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '4',
                'ha_id'                 => '10',        
                'm_id'                  => '2',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '5',
                'ha_id'                 => '11',        
                'm_id'                  => '2',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '5',
                'ha_id'                 => '11',        
                'm_id'                  => '2',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '5',
                'ha_id'                 => '11',        
                'm_id'                  => '2',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '5',
                'ha_id'                 => '12',        
                'm_id'                  => '3',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '5',
                'ha_id'                 => '12',        
                'm_id'                  => '3',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '5',
                'ha_id'                 => '12',        
                'm_id'                  => '3',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '6',
                'ha_id'                 => '13',        
                'm_id'                  => '1',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '6',
                'ha_id'                 => '13',        
                'm_id'                  => '1',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '6',
                'ha_id'                 => '13',        
                'm_id'                  => '1',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '6',
                'ha_id'                 => '14',        
                'm_id'                  => '2',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '6',
                'ha_id'                 => '14',        
                'm_id'                  => '2',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '6',
                'ha_id'                 => '14',        
                'm_id'                  => '2',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '7',
                'ha_id'                 => '15',        
                'm_id'                  => '2',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '7',
                'ha_id'                 => '15',        
                'm_id'                  => '2',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '7',
                'ha_id'                 => '15',        
                'm_id'                  => '2',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '7',
                'ha_id'                 => '16',        
                'm_id'                  => '5',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '7',
                'ha_id'                 => '16',        
                'm_id'                  => '5',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '7',
                'ha_id'                 => '16',        
                'm_id'                  => '5',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '7',
                'ha_id'                 => '17',        
                'm_id'                  => '3',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '7',
                'ha_id'                 => '17',        
                'm_id'                  => '3',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '7',
                'ha_id'                 => '17',        
                'm_id'                  => '3',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '8',
                'ha_id'                 => '18',        
                'm_id'                  => '1',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '8',
                'ha_id'                 => '18',        
                'm_id'                  => '1',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '8',
                'ha_id'                 => '18',        
                'm_id'                  => '1',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '8',
                'ha_id'                 => '19',        
                'm_id'                  => '5',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '8',
                'ha_id'                 => '19',        
                'm_id'                  => '5',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '8',
                'ha_id'                 => '19',        
                'm_id'                  => '5',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '8',
                'ha_id'                 => '20',        
                'm_id'                  => '3',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '8',
                'ha_id'                 => '20',        
                'm_id'                  => '3',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '8',
                'ha_id'                 => '20',        
                'm_id'                  => '3',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '9',
                'ha_id'                 => '21',        
                'm_id'                  => '1',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '9',
                'ha_id'                 => '21',        
                'm_id'                  => '1',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '9',
                'ha_id'                 => '21',        
                'm_id'                  => '1',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '10',
                'ha_id'                 => '22',        
                'm_id'                  => '2',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '10',
                'ha_id'                 => '22',        
                'm_id'                  => '2',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '10',
                'ha_id'                 => '22',        
                'm_id'                  => '2',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '11',
                'ha_id'                 => '23',        
                'm_id'                  => '1',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '11',
                'ha_id'                 => '23',        
                'm_id'                  => '1',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '11',
                'ha_id'                 => '23',        
                'm_id'                  => '1',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '12',
                'ha_id'                 => '24',        
                'm_id'                  => '2',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '12',
                'ha_id'                 => '24',        
                'm_id'                  => '2',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '12',
                'ha_id'                 => '24',        
                'm_id'                  => '2',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '13',
                'ha_id'                 => '25',        
                'm_id'                  => '1',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '13',
                'ha_id'                 => '25',        
                'm_id'                  => '1',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '13',
                'ha_id'                 => '25',        
                'm_id'                  => '1',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '14',
                'ha_id'                 => '26',        
                'm_id'                  => '3',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '14',
                'ha_id'                 => '26',        
                'm_id'                  => '3',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '14',
                'ha_id'                 => '26',        
                'm_id'                  => '3',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '15',
                'ha_id'                 => '27',        
                'm_id'                  => '2',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '15',
                'ha_id'                 => '27',        
                'm_id'                  => '2',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '15',
                'ha_id'                 => '27',        
                'm_id'                  => '2',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '15',
                'ha_id'                 => '28',        
                'm_id'                  => '5',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '15',
                'ha_id'                 => '28',        
                'm_id'                  => '5',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '15',
                'ha_id'                 => '28',        
                'm_id'                  => '5',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '16',
                'ha_id'                 => '29',        
                'm_id'                  => '1',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '16',
                'ha_id'                 => '29',        
                'm_id'                  => '1',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '16',
                'ha_id'                 => '29',        
                'm_id'                  => '1',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '16',
                'ha_id'                 => '30',        
                'm_id'                  => '2',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '16',
                'ha_id'                 => '30',        
                'm_id'                  => '2',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '16',
                'ha_id'                 => '30',        
                'm_id'                  => '2',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '17',
                'ha_id'                 => '31',        
                'm_id'                  => '2',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '17',
                'ha_id'                 => '31',        
                'm_id'                  => '2',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '17',
                'ha_id'                 => '31',        
                'm_id'                  => '2',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '17',
                'ha_id'                 => '32',        
                'm_id'                  => '5',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '17',
                'ha_id'                 => '32',        
                'm_id'                  => '5',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '17',
                'ha_id'                 => '32',        
                'm_id'                  => '5',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '18',
                'ha_id'                 => '33',        
                'm_id'                  => '4',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '18',
                'ha_id'                 => '33',        
                'm_id'                  => '4',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '18',
                'ha_id'                 => '33',        
                'm_id'                  => '4',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '18',
                'ha_id'                 => '34',        
                'm_id'                  => '3',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '18',
                'ha_id'                 => '34',        
                'm_id'                  => '3',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '18',
                'ha_id'                 => '34',        
                'm_id'                  => '3',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '19',
                'ha_id'                 => '35',        
                'm_id'                  => '1',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '19',
                'ha_id'                 => '35',        
                'm_id'                  => '1',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '19',
                'ha_id'                 => '35',        
                'm_id'                  => '1',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '19',
                'ha_id'                 => '36',        
                'm_id'                  => '2',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '19',
                'ha_id'                 => '36',        
                'm_id'                  => '2',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '19',
                'ha_id'                 => '36',        
                'm_id'                  => '2',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '19',
                'ha_id'                 => '37',        
                'm_id'                  => '5',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '19',
                'ha_id'                 => '37',        
                'm_id'                  => '5',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '19',
                'ha_id'                 => '37',        
                'm_id'                  => '5',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '20',
                'ha_id'                 => '38',        
                'm_id'                  => '2',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '20',
                'ha_id'                 => '38',        
                'm_id'                  => '2',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '20',
                'ha_id'                 => '38',        
                'm_id'                  => '2',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '20',
                'ha_id'                 => '39',        
                'm_id'                  => '3',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '20',
                'ha_id'                 => '39',        
                'm_id'                  => '3',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '20',
                'ha_id'                 => '39',        
                'm_id'                  => '3',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '21',
                'ha_id'                 => '40',        
                'm_id'                  => '2',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '21',
                'ha_id'                 => '40',        
                'm_id'                  => '2',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '21',
                'ha_id'                 => '40',        
                'm_id'                  => '2',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '21',
                'ha_id'                 => '41',        
                'm_id'                  => '3',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '21',
                'ha_id'                 => '41',        
                'm_id'                  => '3',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '21',
                'ha_id'                 => '41',        
                'm_id'                  => '3',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '22',
                'ha_id'                 => '42',        
                'm_id'                  => '1',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '22',
                'ha_id'                 => '42',        
                'm_id'                  => '1',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '22',
                'ha_id'                 => '42',        
                'm_id'                  => '1',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '22',
                'ha_id'                 => '43',        
                'm_id'                  => '4',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '22',
                'ha_id'                 => '43',        
                'm_id'                  => '4',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '22',
                'ha_id'                 => '43',        
                'm_id'                  => '4',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '23',
                'ha_id'                 => '44',        
                'm_id'                  => '4',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '23',
                'ha_id'                 => '44',        
                'm_id'                  => '4',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '23',
                'ha_id'                 => '44',        
                'm_id'                  => '4',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '23',
                'ha_id'                 => '45',        
                'm_id'                  => '3',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '23',
                'ha_id'                 => '45',        
                'm_id'                  => '3',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '23',
                'ha_id'                 => '45',        
                'm_id'                  => '3',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '24',
                'ha_id'                 => '46',        
                'm_id'                  => '1',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '24',
                'ha_id'                 => '46',        
                'm_id'                  => '1',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '24',
                'ha_id'                 => '46',        
                'm_id'                  => '1',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '24',
                'ha_id'                 => '47',        
                'm_id'                  => '2',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '24',
                'ha_id'                 => '47',        
                'm_id'                  => '2',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '24',
                'ha_id'                 => '47',        
                'm_id'                  => '2',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '25',
                'ha_id'                 => '48',        
                'm_id'                  => '1',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '25',
                'ha_id'                 => '48',        
                'm_id'                  => '1',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '25',
                'ha_id'                 => '48',        
                'm_id'                  => '1',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '25',
                'ha_id'                 => '49',        
                'm_id'                  => '3',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '25',
                'ha_id'                 => '49',        
                'm_id'                  => '3',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '25',
                'ha_id'                 => '49',        
                'm_id'                  => '3',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '26',
                'ha_id'                 => '50',        
                'm_id'                  => '3',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '26',
                'ha_id'                 => '50',        
                'm_id'                  => '3',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '26',
                'ha_id'                 => '50',        
                'm_id'                  => '3',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '27',
                'ha_id'                 => '51',        
                'm_id'                  => '1',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '27',
                'ha_id'                 => '51',        
                'm_id'                  => '1',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '27',
                'ha_id'                 => '51',        
                'm_id'                  => '1',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '27',
                'ha_id'                 => '52',        
                'm_id'                  => '3',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '27',
                'ha_id'                 => '52',        
                'm_id'                  => '3',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '27',
                'ha_id'                 => '52',        
                'm_id'                  => '3',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '28',
                'ha_id'                 => '53',        
                'm_id'                  => '1',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '28',
                'ha_id'                 => '53',        
                'm_id'                  => '1',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '28',
                'ha_id'                 => '53',        
                'm_id'                  => '1',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '28',
                'ha_id'                 => '54',        
                'm_id'                  => '2',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '28',
                'ha_id'                 => '54',        
                'm_id'                  => '2',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '28',
                'ha_id'                 => '54',        
                'm_id'                  => '2',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '29',
                'ha_id'                 => '55',        
                'm_id'                  => '1',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '29',
                'ha_id'                 => '55',        
                'm_id'                  => '1',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '29',
                'ha_id'                 => '55',        
                'm_id'                  => '1',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '29',
                'ha_id'                 => '56',        
                'm_id'                  => '3',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '29',
                'ha_id'                 => '56',        
                'm_id'                  => '3',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '29',
                'ha_id'                 => '56',        
                'm_id'                  => '3',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '30',
                'ha_id'                 => '57',        
                'm_id'                  => '1',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '30',
                'ha_id'                 => '57',        
                'm_id'                  => '1',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '30',
                'ha_id'                 => '57',        
                'm_id'                  => '1',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '30',
                'ha_id'                 => '58',        
                'm_id'                  => '3',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '30',
                'ha_id'                 => '58',        
                'm_id'                  => '3',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '30',
                'ha_id'                 => '58',        
                'm_id'                  => '3',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '31',
                'ha_id'                 => '59',        
                'm_id'                  => '2',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '31',
                'ha_id'                 => '59',        
                'm_id'                  => '2',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '31',
                'ha_id'                 => '59',        
                'm_id'                  => '2',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '31',
                'ha_id'                 => '60',        
                'm_id'                  => '3',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '31',
                'ha_id'                 => '60',        
                'm_id'                  => '3',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '31',
                'ha_id'                 => '60',        
                'm_id'                  => '3',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '32',
                'ha_id'                 => '61',        
                'm_id'                  => '1',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '32',
                'ha_id'                 => '61',        
                'm_id'                  => '1',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '32',
                'ha_id'                 => '61',        
                'm_id'                  => '1',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '32',
                'ha_id'                 => '62',        
                'm_id'                  => '3',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '32',
                'ha_id'                 => '62',        
                'm_id'                  => '3',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '32',
                'ha_id'                 => '62',        
                'm_id'                  => '3',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '33',
                'ha_id'                 => '63',        
                'm_id'                  => '1',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '33',
                'ha_id'                 => '63',        
                'm_id'                  => '1',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '33',
                'ha_id'                 => '63',        
                'm_id'                  => '1',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '33',
                'ha_id'                 => '64',        
                'm_id'                  => '3',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '33',
                'ha_id'                 => '64',        
                'm_id'                  => '3',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '33',
                'ha_id'                 => '64',        
                'm_id'                  => '3',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '34',
                'ha_id'                 => '65',        
                'm_id'                  => '1',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '34',
                'ha_id'                 => '65',        
                'm_id'                  => '1',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '34',
                'ha_id'                 => '65',        
                'm_id'                  => '1',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '34',
                'ha_id'                 => '66',        
                'm_id'                  => '2',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '34',
                'ha_id'                 => '66',        
                'm_id'                  => '2',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '34',
                'ha_id'                 => '66',        
                'm_id'                  => '2',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '34',
                'ha_id'                 => '67',        
                'm_id'                  => '5',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '34',
                'ha_id'                 => '67',        
                'm_id'                  => '5',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '34',
                'ha_id'                 => '67',        
                'm_id'                  => '5',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '35',
                'ha_id'                 => '68',        
                'm_id'                  => '1',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '35',
                'ha_id'                 => '68',        
                'm_id'                  => '1',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '35',
                'ha_id'                 => '68',        
                'm_id'                  => '1',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '35',
                'ha_id'                 => '69',        
                'm_id'                  => '2',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '35',
                'ha_id'                 => '69',        
                'm_id'                  => '2',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '35',
                'ha_id'                 => '69',        
                'm_id'                  => '2',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '36',
                'ha_id'                 => '70',        
                'm_id'                  => '1',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '36',
                'ha_id'                 => '70',        
                'm_id'                  => '1',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '36',
                'ha_id'                 => '70',        
                'm_id'                  => '1',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '36',
                'ha_id'                 => '71',        
                'm_id'                  => '5',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '36',
                'ha_id'                 => '71',        
                'm_id'                  => '5',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '36',
                'ha_id'                 => '71',        
                'm_id'                  => '5',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '36',
                'ha_id'                 => '72',        
                'm_id'                  => '3',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '36',
                'ha_id'                 => '72',        
                'm_id'                  => '3',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '36',
                'ha_id'                 => '72',        
                'm_id'                  => '3',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '37',
                'ha_id'                 => '73',        
                'm_id'                  => '1',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '37',
                'ha_id'                 => '73',        
                'm_id'                  => '1',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '37',
                'ha_id'                 => '73',        
                'm_id'                  => '1',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '37',
                'ha_id'                 => '74',        
                'm_id'                  => '4',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '37',
                'ha_id'                 => '74',        
                'm_id'                  => '4',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '37',
                'ha_id'                 => '74',        
                'm_id'                  => '4',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '37',
                'ha_id'                 => '75',        
                'm_id'                  => '3',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '5',        
            ],
            [
                'sp_id'                 => '37',
                'ha_id'                 => '75',        
                'm_id'                  => '3',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '7',        
            ],
            [
                'sp_id'                 => '37',
                'ha_id'                 => '75',        
                'm_id'                  => '3',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '10',        
            ],
            [
                'sp_id'                 => '38',
                'ha_id'                 => '76',        
                'm_id'                  => '5',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '38',
                'ha_id'                 => '76',        
                'm_id'                  => '5',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '38',
                'ha_id'                 => '76',        
                'm_id'                  => '5',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '38',
                'ha_id'                 => '77',        
                'm_id'                  => '3',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '38',
                'ha_id'                 => '77',        
                'm_id'                  => '3',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '38',
                'ha_id'                 => '77',        
                'm_id'                  => '3',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '39',
                'ha_id'                 => '78',        
                'm_id'                  => '1',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '39',
                'ha_id'                 => '78',        
                'm_id'                  => '1',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '39',
                'ha_id'                 => '78',        
                'm_id'                  => '1',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '39',
                'ha_id'                 => '79',        
                'm_id'                  => '2',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '39',
                'ha_id'                 => '79',        
                'm_id'                  => '2',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '39',
                'ha_id'                 => '79',        
                'm_id'                  => '2',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '40',
                'ha_id'                 => '80',        
                'm_id'                  => '1',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '40',
                'ha_id'                 => '80',        
                'm_id'                  => '1',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '40',
                'ha_id'                 => '80',        
                'm_id'                  => '1',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '40',
                'ha_id'                 => '81',        
                'm_id'                  => '5',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '40',
                'ha_id'                 => '81',        
                'm_id'                  => '5',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '40',
                'ha_id'                 => '81',        
                'm_id'                  => '5',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '40',
                'ha_id'                 => '82',        
                'm_id'                  => '3',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '40',
                'ha_id'                 => '82',        
                'm_id'                  => '3',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '40',
                'ha_id'                 => '82',        
                'm_id'                  => '3',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '41',
                'ha_id'                 => '83',        
                'm_id'                  => '2',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '41',
                'ha_id'                 => '83',        
                'm_id'                  => '2',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '41',
                'ha_id'                 => '83',        
                'm_id'                  => '2',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '41',
                'ha_id'                 => '84',        
                'm_id'                  => '3',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '41',
                'ha_id'                 => '84',        
                'm_id'                  => '3',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '41',
                'ha_id'                 => '84',        
                'm_id'                  => '3',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '42',
                'ha_id'                 => '85',        
                'm_id'                  => '5',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '42',
                'ha_id'                 => '85',        
                'm_id'                  => '5',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '42',
                'ha_id'                 => '85',        
                'm_id'                  => '5',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '42',
                'ha_id'                 => '86',        
                'm_id'                  => '1',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '42',
                'ha_id'                 => '86',        
                'm_id'                  => '1',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '42',
                'ha_id'                 => '86',        
                'm_id'                  => '1',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '43',
                'ha_id'                 => '87',        
                'm_id'                  => '1',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '43',
                'ha_id'                 => '87',        
                'm_id'                  => '1',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '43',
                'ha_id'                 => '87',        
                'm_id'                  => '1',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '43',
                'ha_id'                 => '88',        
                'm_id'                  => '2',        
                'size_id'               => '1',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '43',
                'ha_id'                 => '88',        
                'm_id'                  => '2',        
                'size_id'               => '2',        
                'ctsp_soluong'          => '30',        
            ],
            [
                'sp_id'                 => '43',
                'ha_id'                 => '88',        
                'm_id'                  => '2',        
                'size_id'               => '3',        
                'ctsp_soluong'          => '30',        
            ],
        ];
        DB::table('chitietsanpham')->insert($list);
    }
}
