<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ChiTietPhieuNhapTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $list=[
            //phiếu nhập kho 1
            [
                'pnk_id'            => '1',
                'sp_id'             => '1',
                'm_id'              => '1', //mau den
                'size_id'           => '1', //size S
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],    
            [
                'pnk_id'            => '1',
                'sp_id'             => '1',
                'm_id'              => '2', //mau trang
                'size_id'           => '1', 
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],    
            [
                'pnk_id'            => '1',
                'sp_id'             => '1',
                'm_id'              => '1', 
                'size_id'           => '2', // size M
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],    
            [
                'pnk_id'            => '1',
                'sp_id'             => '1',
                'm_id'              => '2',
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],    
            [
                'pnk_id'            => '1',
                'sp_id'             => '1',
                'm_id'              => '1',
                'size_id'           => '3', //size L
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],    
            [
                'pnk_id'            => '1',
                'sp_id'             => '1',
                'm_id'              => '2',
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],    
            [
                'pnk_id'            => '1',
                'sp_id'             => '2',
                'm_id'              => '1',
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],    
            [
                'pnk_id'            => '1',
                'sp_id'             => '2',
                'm_id'              => '5', //màu vàng
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],    
            [
                'pnk_id'            => '1',
                'sp_id'             => '2',
                'm_id'              => '3', //màu xanh
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],    
            [
                'pnk_id'            => '1',
                'sp_id'             => '2',
                'm_id'              => '1', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],    
            [
                'pnk_id'            => '1',
                'sp_id'             => '2',
                'm_id'              => '5', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],    
            [
                'pnk_id'            => '1',
                'sp_id'             => '2',
                'm_id'              => '3', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],    
            [
                'pnk_id'            => '1',
                'sp_id'             => '2',
                'm_id'              => '1', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],    
            [
                'pnk_id'            => '1',
                'sp_id'             => '2',
                'm_id'              => '5', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],    
            [
                'pnk_id'            => '1',
                'sp_id'             => '2',
                'm_id'              => '3', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],    
            [
                'pnk_id'            => '1',
                'sp_id'             => '3',
                'm_id'              => '1', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],    
            [
                'pnk_id'            => '1',
                'sp_id'             => '3',
                'm_id'              => '1', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],    
            [
                'pnk_id'            => '1',
                'sp_id'             => '3',
                'm_id'              => '1', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],    
            [
                'pnk_id'            => '1',
                'sp_id'             => '3',
                'm_id'              => '2', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],       
            [
                'pnk_id'            => '1',
                'sp_id'             => '3',
                'm_id'              => '2', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],    
            [
                'pnk_id'            => '1',
                'sp_id'             => '3',
                'm_id'              => '2', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],    
            [
                'pnk_id'            => '1',
                'sp_id'             => '3',
                'm_id'              => '3', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],    
            [
                'pnk_id'            => '1',
                'sp_id'             => '3',
                'm_id'              => '3', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],    
            [
                'pnk_id'            => '1',
                'sp_id'             => '3',
                'm_id'              => '3', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],  

            //phiếu nhập kho 2
            [
                'pnk_id'            => '2',
                'sp_id'             => '4',
                'm_id'              => '1', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],    
            [
                'pnk_id'            => '2',
                'sp_id'             => '4',
                'm_id'              => '1', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],    
            [
                'pnk_id'            => '2',
                'sp_id'             => '4',
                'm_id'              => '1', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],    
            [
                'pnk_id'            => '2',
                'sp_id'             => '4',
                'm_id'              => '2', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],    
            [
                'pnk_id'            => '2',
                'sp_id'             => '4',
                'm_id'              => '2', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],    
            [
                'pnk_id'            => '2',
                'sp_id'             => '4',
                'm_id'              => '2', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],    
            [
                'pnk_id'            => '2',
                'sp_id'             => '5',
                'm_id'              => '2', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],    
            [
                'pnk_id'            => '2',
                'sp_id'             => '5',
                'm_id'              => '2', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],    
            [
                'pnk_id'            => '2',
                'sp_id'             => '5',
                'm_id'              => '2', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],    
            [
                'pnk_id'            => '2',
                'sp_id'             => '5',
                'm_id'              => '3', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],    
            [
                'pnk_id'            => '2',
                'sp_id'             => '5',
                'm_id'              => '3', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],    
            [
                'pnk_id'            => '2',
                'sp_id'             => '5',
                'm_id'              => '3', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],    

            //phiếu nhập kho 3
            [
                'pnk_id'            => '3',
                'sp_id'             => '6',
                'm_id'              => '1', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '180000',
            ],
            [
                'pnk_id'            => '3',
                'sp_id'             => '6',
                'm_id'              => '1', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '180000',
            ],
            [
                'pnk_id'            => '3',
                'sp_id'             => '6',
                'm_id'              => '1', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '180000',
            ],
            [
                'pnk_id'            => '3',
                'sp_id'             => '6',
                'm_id'              => '2', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '180000',
            ],
            [
                'pnk_id'            => '3',
                'sp_id'             => '6',
                'm_id'              => '2', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '180000',
            ],
            [
                'pnk_id'            => '3',
                'sp_id'             => '6',
                'm_id'              => '2', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '180000',
            ],
            [
                'pnk_id'            => '3',
                'sp_id'             => '7',
                'm_id'              => '2', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '200000',
            ],
            [
                'pnk_id'            => '3',
                'sp_id'             => '7',
                'm_id'              => '2', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '200000',
            ],
            [
                'pnk_id'            => '3',
                'sp_id'             => '7',
                'm_id'              => '2', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '200000',
            ],
            [
                'pnk_id'            => '3',
                'sp_id'             => '7',
                'm_id'              => '5', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '200000',
            ],
            [
                'pnk_id'            => '3',
                'sp_id'             => '7',
                'm_id'              => '5', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '200000',
            ],
            [
                'pnk_id'            => '3',
                'sp_id'             => '7',
                'm_id'              => '5', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '200000',
            ],
            [
                'pnk_id'            => '3',
                'sp_id'             => '7',
                'm_id'              => '3', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '200000',
            ],
            [
                'pnk_id'            => '3',
                'sp_id'             => '8',
                'm_id'              => '1', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '170000',
            ],
            [
                'pnk_id'            => '3',
                'sp_id'             => '8',
                'm_id'              => '1', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '170000',
            ],
            [
                'pnk_id'            => '3',
                'sp_id'             => '8',
                'm_id'              => '1', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '170000',
            ],
            [
                'pnk_id'            => '3',
                'sp_id'             => '8',
                'm_id'              => '5', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '170000',
            ],
            [
                'pnk_id'            => '3',
                'sp_id'             => '8',
                'm_id'              => '5', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '170000',
            ],
            [
                'pnk_id'            => '3',
                'sp_id'             => '8',
                'm_id'              => '5', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '170000',
            ],
            [
                'pnk_id'            => '3',
                'sp_id'             => '8',
                'm_id'              => '3', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '170000',
            ],
            [
                'pnk_id'            => '3',
                'sp_id'             => '8',
                'm_id'              => '3', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '170000',
            ],
            [
                'pnk_id'            => '3',
                'sp_id'             => '8',
                'm_id'              => '3', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '170000',
            ],

            // phiếu nhập kho 4
            [
                'pnk_id'            => '4',
                'sp_id'             => '9',
                'm_id'              => '1', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '250000',
            ],
            [
                'pnk_id'            => '4',
                'sp_id'             => '9',
                'm_id'              => '1', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '250000',
            ],
            [
                'pnk_id'            => '4',
                'sp_id'             => '9',
                'm_id'              => '1', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '250000',
            ],
            [
                'pnk_id'            => '4',
                'sp_id'             => '10',
                'm_id'              => '2', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '250000',
            ],
            [
                'pnk_id'            => '4',
                'sp_id'             => '10',
                'm_id'              => '2', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '250000',
            ],
            [
                'pnk_id'            => '4',
                'sp_id'             => '10',
                'm_id'              => '2', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '250000',
            ],
            [
                'pnk_id'            => '4',
                'sp_id'             => '11',
                'm_id'              => '1', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '250000',
            ],
            [
                'pnk_id'            => '4',
                'sp_id'             => '11',
                'm_id'              => '1', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '250000',
            ],
            [
                'pnk_id'            => '4',
                'sp_id'             => '11',
                'm_id'              => '1', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '250000',
            ],
            [
                'pnk_id'            => '4',
                'sp_id'             => '12',
                'm_id'              => '2', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '215000',
            ],
            [
                'pnk_id'            => '4',
                'sp_id'             => '12',
                'm_id'              => '2', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '215000',
            ],
            [
                'pnk_id'            => '4',
                'sp_id'             => '12',
                'm_id'              => '2', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '215000',
            ],
            [
                'pnk_id'            => '4',
                'sp_id'             => '13',
                'm_id'              => '1', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '215000',
            ],
            [
                'pnk_id'            => '4',
                'sp_id'             => '13',
                'm_id'              => '1', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '215000',
            ],
            [
                'pnk_id'            => '4',
                'sp_id'             => '13',
                'm_id'              => '1', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '215000',
            ],
            [
                'pnk_id'            => '4',
                'sp_id'             => '14',
                'm_id'              => '3', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '215000',
            ],
            [
                'pnk_id'            => '4',
                'sp_id'             => '14',
                'm_id'              => '3', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '215000',
            ],
            [
                'pnk_id'            => '4',
                'sp_id'             => '14',
                'm_id'              => '3', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '215000',
            ],

            // phiếu nhập kho 5
            [
                'pnk_id'            => '5',
                'sp_id'             => '15',
                'm_id'              => '2', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],
            [
                'pnk_id'            => '5',
                'sp_id'             => '15',
                'm_id'              => '2', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],
            [
                'pnk_id'            => '5',
                'sp_id'             => '15',
                'm_id'              => '2', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],
            [
                'pnk_id'            => '5',
                'sp_id'             => '15',
                'm_id'              => '5', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],
            [
                'pnk_id'            => '5',
                'sp_id'             => '15',
                'm_id'              => '5', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],
            [
                'pnk_id'            => '5',
                'sp_id'             => '15',
                'm_id'              => '5', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],
            [
                'pnk_id'            => '5',
                'sp_id'             => '16',
                'm_id'              => '1', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],
            [
                'pnk_id'            => '5',
                'sp_id'             => '16',
                'm_id'              => '1', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],
            [
                'pnk_id'            => '5',
                'sp_id'             => '16',
                'm_id'              => '1', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],
            [
                'pnk_id'            => '5',
                'sp_id'             => '16',
                'm_id'              => '2', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],
            [
                'pnk_id'            => '5',
                'sp_id'             => '16',
                'm_id'              => '2', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],
            [
                'pnk_id'            => '5',
                'sp_id'             => '16',
                'm_id'              => '2', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],
            [
                'pnk_id'            => '5',
                'sp_id'             => '17',
                'm_id'              => '2', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '80000',
            ],
            [
                'pnk_id'            => '5',
                'sp_id'             => '17',
                'm_id'              => '2', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '80000',
            ],
            [
                'pnk_id'            => '5',
                'sp_id'             => '17',
                'm_id'              => '2', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '80000',
            ],
            [
                'pnk_id'            => '5',
                'sp_id'             => '17',
                'm_id'              => '5', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '80000',
            ],
            [
                'pnk_id'            => '5',
                'sp_id'             => '17',
                'm_id'              => '5', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '80000',
            ],
            [
                'pnk_id'            => '5',
                'sp_id'             => '17',
                'm_id'              => '5', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '80000',
            ],
            [
                'pnk_id'            => '5',
                'sp_id'             => '18',
                'm_id'              => '4', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],
            [
                'pnk_id'            => '5',
                'sp_id'             => '18',
                'm_id'              => '4', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],
            [
                'pnk_id'            => '5',
                'sp_id'             => '18',
                'm_id'              => '4', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],
            [
                'pnk_id'            => '5',
                'sp_id'             => '18',
                'm_id'              => '3', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],
            [
                'pnk_id'            => '5',
                'sp_id'             => '18',
                'm_id'              => '3', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],
            [
                'pnk_id'            => '5',
                'sp_id'             => '18',
                'm_id'              => '3', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],
            [
                'pnk_id'            => '5',
                'sp_id'             => '19',
                'm_id'              => '1', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],
            [
                'pnk_id'            => '5',
                'sp_id'             => '19',
                'm_id'              => '1', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],
            [
                'pnk_id'            => '5',
                'sp_id'             => '19',
                'm_id'              => '1', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],
            [
                'pnk_id'            => '5',
                'sp_id'             => '19',
                'm_id'              => '2', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],
            [
                'pnk_id'            => '5',
                'sp_id'             => '19',
                'm_id'              => '2', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],
            [
                'pnk_id'            => '5',
                'sp_id'             => '19',
                'm_id'              => '2', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],
            [
                'pnk_id'            => '5',
                'sp_id'             => '19',
                'm_id'              => '5', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],
            [
                'pnk_id'            => '5',
                'sp_id'             => '19',
                'm_id'              => '5', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],
            [
                'pnk_id'            => '5',
                'sp_id'             => '19',
                'm_id'              => '5', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '100000',
            ],

            // phiếu nhập kho 6
            [
                'pnk_id'            => '6',
                'sp_id'             => '20',
                'm_id'              => '2', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '130000',
            ],
            [
                'pnk_id'            => '6',
                'sp_id'             => '20',
                'm_id'              => '2', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '130000',
            ],
            [
                'pnk_id'            => '6',
                'sp_id'             => '20',
                'm_id'              => '2', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '130000',
            ],
            [
                'pnk_id'            => '6',
                'sp_id'             => '20',
                'm_id'              => '3', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '130000',
            ],
            [
                'pnk_id'            => '6',
                'sp_id'             => '20',
                'm_id'              => '3', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '130000',
            ],
            [
                'pnk_id'            => '6',
                'sp_id'             => '20',
                'm_id'              => '3', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '130000',
            ],
            [
                'pnk_id'            => '6',
                'sp_id'             => '21',
                'm_id'              => '2', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '130000',
            ],
            [
                'pnk_id'            => '6',
                'sp_id'             => '21',
                'm_id'              => '2', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '130000',
            ],
            [
                'pnk_id'            => '6',
                'sp_id'             => '21',
                'm_id'              => '2', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '130000',
            ],
            [
                'pnk_id'            => '6',
                'sp_id'             => '21',
                'm_id'              => '3', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '130000',
            ],
            [
                'pnk_id'            => '6',
                'sp_id'             => '21',
                'm_id'              => '3', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '130000',
            ],
            [
                'pnk_id'            => '6',
                'sp_id'             => '21',
                'm_id'              => '3', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '130000',
            ],
            [
                'pnk_id'            => '6',
                'sp_id'             => '22',
                'm_id'              => '1', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '130000',
            ],
            [
                'pnk_id'            => '6',
                'sp_id'             => '22',
                'm_id'              => '1', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '130000',
            ],
            [
                'pnk_id'            => '6',
                'sp_id'             => '22',
                'm_id'              => '1', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '130000',
            ],
            [
                'pnk_id'            => '6',
                'sp_id'             => '22',
                'm_id'              => '4', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '130000',
            ],
            [
                'pnk_id'            => '6',
                'sp_id'             => '22',
                'm_id'              => '4', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '130000',
            ],
            [
                'pnk_id'            => '6',
                'sp_id'             => '22',
                'm_id'              => '4', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '130000',
            ],
            [
                'pnk_id'            => '6',
                'sp_id'             => '23',
                'm_id'              => '4', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '130000',
            ],
            [
                'pnk_id'            => '6',
                'sp_id'             => '23',
                'm_id'              => '4', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '130000',
            ],
            [
                'pnk_id'            => '6',
                'sp_id'             => '23',
                'm_id'              => '4', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '130000',
            ],
            [
                'pnk_id'            => '6',
                'sp_id'             => '23',
                'm_id'              => '3', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '130000',
            ],
            [
                'pnk_id'            => '6',
                'sp_id'             => '23',
                'm_id'              => '3', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '130000',
            ],
            [
                'pnk_id'            => '6',
                'sp_id'             => '23',
                'm_id'              => '3', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '130000',
            ],
            [
                'pnk_id'            => '6',
                'sp_id'             => '24',
                'm_id'              => '1', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '120000',
            ],
            [
                'pnk_id'            => '6',
                'sp_id'             => '24',
                'm_id'              => '1', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '120000',
            ],
            [
                'pnk_id'            => '6',
                'sp_id'             => '24',
                'm_id'              => '1', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '120000',
            ],
            [
                'pnk_id'            => '6',
                'sp_id'             => '24',
                'm_id'              => '2', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '120000',
            ],
            [
                'pnk_id'            => '6',
                'sp_id'             => '24',
                'm_id'              => '2', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '120000',
            ],
            [
                'pnk_id'            => '6',
                'sp_id'             => '24',
                'm_id'              => '2', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '120000',
            ],

            //phiếu nhập kho 7
            [
                'pnk_id'            => '7',
                'sp_id'             => '25',
                'm_id'              => '1', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '200000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '25',
                'm_id'              => '1', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '200000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '25',
                'm_id'              => '1', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '200000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '25',
                'm_id'              => '3', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '200000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '25',
                'm_id'              => '3', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '200000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '25',
                'm_id'              => '3', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '200000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '26',
                'm_id'              => '3', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '200000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '26',
                'm_id'              => '3', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '200000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '26',
                'm_id'              => '3', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '200000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '27',
                'm_id'              => '1', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '200000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '27',
                'm_id'              => '1', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '200000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '27',
                'm_id'              => '1', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '200000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '27',
                'm_id'              => '3', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '200000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '27',
                'm_id'              => '3', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '200000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '27',
                'm_id'              => '3', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '200000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '28',
                'm_id'              => '1', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '200000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '28',
                'm_id'              => '1', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '200000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '28',
                'm_id'              => '1', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '200000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '28',
                'm_id'              => '2', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '200000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '28',
                'm_id'              => '2', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '200000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '28',
                'm_id'              => '2', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '200000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '29',
                'm_id'              => '1', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '200000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '29',
                'm_id'              => '1', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '200000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '29',
                'm_id'              => '1', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '200000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '29',
                'm_id'              => '3', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '200000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '29',
                'm_id'              => '3', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '200000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '29',
                'm_id'              => '3', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '200000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '30',
                'm_id'              => '1', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '250000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '30',
                'm_id'              => '1', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '250000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '30',
                'm_id'              => '1', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '250000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '30',
                'm_id'              => '3', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '250000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '30',
                'm_id'              => '3', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '250000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '30',
                'm_id'              => '3', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '250000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '31',
                'm_id'              => '2', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '250000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '31',
                'm_id'              => '2', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '250000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '31',
                'm_id'              => '2', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '250000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '31',
                'm_id'              => '3', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '250000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '31',
                'm_id'              => '3', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '250000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '31',
                'm_id'              => '3', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '250000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '32',
                'm_id'              => '1', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '250000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '32',
                'm_id'              => '1', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '250000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '32',
                'm_id'              => '1', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '250000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '32',
                'm_id'              => '3', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '250000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '32',
                'm_id'              => '3', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '250000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '32',
                'm_id'              => '3', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '250000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '33',
                'm_id'              => '1', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '250000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '33',
                'm_id'              => '1', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '250000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '33',
                'm_id'              => '1', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '250000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '33',
                'm_id'              => '3', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '250000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '33',
                'm_id'              => '3', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '250000',
            ],
            [
                'pnk_id'            => '7',
                'sp_id'             => '33',
                'm_id'              => '3', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '250000',
            ],

            //phiếu nhập kho 8
            [
                'pnk_id'            => '8',
                'sp_id'             => '34',
                'm_id'              => '1', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '34',
                'm_id'              => '1', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '34',
                'm_id'              => '1', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '34',
                'm_id'              => '2', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '34',
                'm_id'              => '2', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '34',
                'm_id'              => '2', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '34',
                'm_id'              => '5', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '34',
                'm_id'              => '5', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '34',
                'm_id'              => '5', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '35',
                'm_id'              => '1', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '35',
                'm_id'              => '1', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '35',
                'm_id'              => '1', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '35',
                'm_id'              => '2', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '35',
                'm_id'              => '2', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '35',
                'm_id'              => '2', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '36',
                'm_id'              => '1', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '36',
                'm_id'              => '1', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '36',
                'm_id'              => '1', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '36',
                'm_id'              => '5', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '36',
                'm_id'              => '5', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '36',
                'm_id'              => '5', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '36',
                'm_id'              => '3', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '36',
                'm_id'              => '3', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '36',
                'm_id'              => '3', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '150000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '37',
                'm_id'              => '1', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '180000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '37',
                'm_id'              => '1', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '180000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '37',
                'm_id'              => '1', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '180000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '37',
                'm_id'              => '4', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '180000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '37',
                'm_id'              => '4', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '180000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '37',
                'm_id'              => '4', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '180000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '37',
                'm_id'              => '3', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '180000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '37',
                'm_id'              => '3', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '180000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '37',
                'm_id'              => '3', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '180000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '38',
                'm_id'              => '5', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '180000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '38',
                'm_id'              => '5', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '180000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '38',
                'm_id'              => '5', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '180000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '38',
                'm_id'              => '3', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '180000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '38',
                'm_id'              => '3', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '180000',
            ],
            [
                'pnk_id'            => '8',
                'sp_id'             => '38',
                'm_id'              => '3', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '180000',
            ],

            //phiếu nhập kho 9
            [
                'pnk_id'            => '9',
                'sp_id'             => '39',
                'm_id'              => '1', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '300000',
            ],
            [
                'pnk_id'            => '9',
                'sp_id'             => '39',
                'm_id'              => '1', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '300000',
            ],
            [
                'pnk_id'            => '9',
                'sp_id'             => '39',
                'm_id'              => '1', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '300000',
            ],
            [
                'pnk_id'            => '9',
                'sp_id'             => '39',
                'm_id'              => '2', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '300000',
            ],
            [
                'pnk_id'            => '9',
                'sp_id'             => '39',
                'm_id'              => '2', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '300000',
            ],
            [
                'pnk_id'            => '9',
                'sp_id'             => '39',
                'm_id'              => '2', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '300000',
            ],
            [
                'pnk_id'            => '9',
                'sp_id'             => '40',
                'm_id'              => '1', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '400000',
            ],
            [
                'pnk_id'            => '9',
                'sp_id'             => '40',
                'm_id'              => '1', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '400000',
            ],
            [
                'pnk_id'            => '9',
                'sp_id'             => '40',
                'm_id'              => '1', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '400000',
            ],
            [
                'pnk_id'            => '9',
                'sp_id'             => '40',
                'm_id'              => '5', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '400000',
            ],
            [
                'pnk_id'            => '9',
                'sp_id'             => '40',
                'm_id'              => '5', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '400000',
            ],
            [
                'pnk_id'            => '9',
                'sp_id'             => '40',
                'm_id'              => '5', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '400000',
            ],
            [
                'pnk_id'            => '9',
                'sp_id'             => '40',
                'm_id'              => '3', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '400000',
            ],
            [
                'pnk_id'            => '9',
                'sp_id'             => '40',
                'm_id'              => '3', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '400000',
            ],
            [
                'pnk_id'            => '9',
                'sp_id'             => '40',
                'm_id'              => '3', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '400000',
            ],
            [
                'pnk_id'            => '9',
                'sp_id'             => '41',
                'm_id'              => '2', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '300000',
            ],
            [
                'pnk_id'            => '9',
                'sp_id'             => '41',
                'm_id'              => '2', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '300000',
            ],
            [
                'pnk_id'            => '9',
                'sp_id'             => '41',
                'm_id'              => '2', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '300000',
            ],
            [
                'pnk_id'            => '9',
                'sp_id'             => '41',
                'm_id'              => '3', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '300000',
            ],
            [
                'pnk_id'            => '9',
                'sp_id'             => '41',
                'm_id'              => '3', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '300000',
            ],
            [
                'pnk_id'            => '9',
                'sp_id'             => '41',
                'm_id'              => '3', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '300000',
            ],
            
            [
                'pnk_id'            => '9',
                'sp_id'             => '42',
                'm_id'              => '5', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '400000',
            ],
            [
                'pnk_id'            => '9',
                'sp_id'             => '42',
                'm_id'              => '5', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '400000',
            ],
            [
                'pnk_id'            => '9',
                'sp_id'             => '42',
                'm_id'              => '5', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '400000',
            ],
            [
                'pnk_id'            => '9',
                'sp_id'             => '42',
                'm_id'              => '1', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '400000',
            ],
            [
                'pnk_id'            => '9',
                'sp_id'             => '42',
                'm_id'              => '1', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '400000',
            ],
            [
                'pnk_id'            => '9',
                'sp_id'             => '42',
                'm_id'              => '1', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '400000',
            ],
            [
                'pnk_id'            => '9',
                'sp_id'             => '43',
                'm_id'              => '5', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '300000',
            ],
            [
                'pnk_id'            => '9',
                'sp_id'             => '43',
                'm_id'              => '5', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '300000',
            ],
            [
                'pnk_id'            => '9',
                'sp_id'             => '43',
                'm_id'              => '5', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '300000',
            ],
            [
                'pnk_id'            => '9',
                'sp_id'             => '43',
                'm_id'              => '3', 
                'size_id'           => '1',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '300000',
            ],
            [
                'pnk_id'            => '9',
                'sp_id'             => '43',
                'm_id'              => '3', 
                'size_id'           => '2',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '300000',
            ],
            [
                'pnk_id'            => '9',
                'sp_id'             => '43',
                'm_id'              => '3', 
                'size_id'           => '3',
                'ctpn_soluong'      => '10',
                'ctpn_gianhap'      => '300000',
            ],
        ];
        DB::table('chitietphieunhap')->insert($list);
    }
}
