<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SanPhamTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
   
   public function run()
    {
        $today = new DateTime();
        $list=[
            [
                'sp_id'             => '1',
                'sp_ten'            => 'ÁO THUN B1',
                  
                //'sp_hinh'           => 'aothunB1_den.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Áo thun B1 chất liệu cotton mềm mịn, mang lại cảm giác dễ chịu cho người mặc, kèm với logo THE ROSE đơn giản giúp các chàng trai trở nên năng động hơn.',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '200000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '1',    
                'km_id'             => '3',    
                'kho_id'            => '1',    
            ],
            [
                'sp_id'             => '2',
                'sp_ten'            => 'ÁO THUN B2',
                   
               // 'sp_hinh'           => 'aothunB2_xanh.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Áo thun B2 chất liệu cotton mềm mịn, với gam màu trơn tươi sáng mang lại cảm giác tươi mới cho người mặc.',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '200000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '1',    
                'km_id'             => NULL,    
                'kho_id'            => '1',    
            ],
            [
                'sp_id'             => '3',
                'sp_ten'            => 'ÁO THUN B3',
                  
                //'sp_hinh'           => 'aothunB3_trang.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Áo thun B3 chất liệu cotton mềm mịn, kèm những họa tiết dễ thương mang lại cảm giác tươi trẻ cho người mặc.',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '250000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '1',    
                'km_id'             => NULL,    
                'kho_id'            => '1',    
            ],
            [
                'sp_id'             => '4',
                'sp_ten'            => 'ÁO THUN B4',
                   
               // 'sp_hinh'           => 'aothunB4_trang.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Áo thun B4 chất liệu cotton mềm mịn, mang lại cảm giác dễ chịu cho người mặc, kèm với logo đơn giản giúp các chàng trai trở nên năng động hơn.',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '200000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '1',    
                'km_id'             => NULL,    
                'kho_id'            => '1',    
            ],
            [
                'sp_id'             => '5',
                'sp_ten'            => 'ÁO THUN B5',
                   
                //'sp_hinh'           => 'aothunB5_xanh.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Áo thun B5 chất liệu cotton mềm mịn, kèm những họa tiết lớn mang lại cảm giác năng động cho người mặc',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '250000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '1',    
                'km_id'             => NULL,    
                'kho_id'            => '1',    
            ],
            [
                'sp_id'             => '6',
                'sp_ten'            => 'ÁO SƠ MI B1',
                 
                //'sp_hinh'           => 'aosomiB1_trắng.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Áo sơ mi B1 chất liệu mềm mịn, màu trơn lịch lãm, thích hợp cho các buổi họp mặt và sự kiện.',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '280000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '2',    
                'km_id'             => NULL,    
                'kho_id'            => '1',    
            ],
            [
                'sp_id'             => '7',
                'sp_ten'            => 'ÁO SƠ MI B2',
                   
                //'sp_hinh'           => 'aosomiB2_xanh.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Áo sơ mi B2 tay dài, phối màu lịch lãm, thích hợp cho các buổi những buổi đi chơi, hẹn hò và cả những buổi họp mặt và sự kiện.',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '300000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '2',    
                'km_id'             => '3',    
                'kho_id'            => '1',    
            ],
            [
                'sp_id'             => '8',
                'sp_ten'            => 'ÁO SƠ MI B3',
                 
                //'sp_hinh'           => 'aosomiB3_xanh.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Áo sơ mi B3 tay ngắn, phối màu loang cực đẹp, thích hợp cho các buổi những buổi đi chơi, hẹn hò, mang lại cảm giác cool ngầu cho người mặc. ',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '270000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '2',    
                'km_id'             => NULL,    
                'kho_id'            => '1',    
            ],
            [
                'sp_id'             => '9',
                'sp_ten'            => 'QUẦN JEAN B1',
                  
                //'sp_hinh'           => 'quanjeanB1_den.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Quần jean B1, chất liệu co dãn, mang lại cảm giác thoải mái cho người mặc.',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '350000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '3',    
                'km_id'             => '2',    
                'kho_id'            => '1',    
            ],
            [
                'sp_id'             => '10',
                'sp_ten'            => 'QUẦN JEAN B2',
                 
                //'sp_hinh'           => 'quanjeanB2_trang.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Quần jean B2, chất liệu co dãn, mang lại cảm giác thoải mái cho người mặc.',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '350000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '3',    
                'km_id'             => NULL,    
                'kho_id'            => '1',    
            ],
            [
                'sp_id'             => '11',
                'sp_ten'            => 'QUẦN JEAN B3',
                   
                //'sp_hinh'           => 'quanjeanB3_den.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Quần jean B3, chất liệu co dãn, mang lại cảm giác thoải mái cho người mặc.',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '350000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '3',    
                'km_id'             => '3',    
                'kho_id'            => '1',    
            ],
            [
                'sp_id'             => '12',
                'sp_ten'            => 'QUẦN KAKI B1',
                   
               // 'sp_hinh'           => 'quankakiB1_trang.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Quần kaki B1, chất liệu co dãn, mang lại cảm giác thoải mái cho người mặc.',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '315000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '4',    
                'km_id'             => NULL,    
                'kho_id'            => '1',    
            ],
            [
                'sp_id'             => '13',
                'sp_ten'            => 'QUẦN KAKI B2',
                  
               // 'sp_hinh'           => 'quankakiB2_den.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Quần kaki B2, chất liệu co dãn, mang lại cảm giác thoải mái cho người mặc.',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '315000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '4',    
                'km_id'             => NULL,    
                'kho_id'            => '1',    
            ],
            [
                'sp_id'             => '14',
                'sp_ten'            => 'QUẦN KAKI B3',
                 
               // 'sp_hinh'           => 'quankakiB3_xanh.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Quần kaki B3, chất liệu co dãn, mang lại cảm giác thoải mái cho người mặc.',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '315000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '4',    
                'km_id'             => '2',    
                'kho_id'            => '1',    
            ],
            [
                'sp_id'             => '15',
                'sp_ten'            => 'ÁO THUN G1',
                   
                //'sp_hinh'           => 'aothunG1_trang.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Áo thun G1, với họa tiết đơn giản cùng những gam màu đơn, giúp người mặc mang lại cảm giác tươi trẻ.',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '200000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '5',    
                'km_id'             => '3',    
                'kho_id'            => '2',    
            ],
            [
                'sp_id'             => '16',
                'sp_ten'            => 'ÁO THUN G2',
                    
                //'sp_hinh'           => 'aothunG2_den.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Áo thun G2, với họa tiết đơn giản cùng những gam màu đơn, giúp người mặc mang lại cảm giác tươi trẻ.',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '200000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '5',    
                'km_id'             => NULL,    
                'kho_id'            => '2',    
            ],
            [
                'sp_id'             => '17',
                'sp_ten'            => 'ÁO THUN G3',
                  
                //'sp_hinh'           => 'aothunG3_trang.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Áo thun G3, với họa tiết đơn giản cùng những gam màu đơn, giúp người mặc mang lại cảm giác tươi trẻ.',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '180000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '5',    
                'km_id'             => NULL,    
                'kho_id'            => '2',    
            ],
            [
                'sp_id'             => '18',
                'sp_ten'            => 'ÁO THUN G4',
                  
                //'sp_hinh'           => 'aothunG4_xanh.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Áo thun G4, với các đường kẻ sọc đơn giản, giúp người mặc mang lại cảm giác tươi trẻ.',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '200000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '5',    
                'km_id'             => NULL,    
                'kho_id'            => '2',    
            ],
            [
                'sp_id'             => '19',
                'sp_ten'            => 'ÁO THUN G5',
                   
               // 'sp_hinh'           => 'aothunG5_den.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Áo thun G5, với họa tiết bông cúc xu hướng, giúp người mặc mang lại cảm giác tươi trẻ.',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '200000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '5',    
                'km_id'             => NULL,    
                'kho_id'            => '2',    
            ],
            [
                'sp_id'             => '20',
                'sp_ten'            => 'ÁO SƠ MI G1',
                   
                //'sp_hinh'           => 'somiG1_trang.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Áo sơ mi G1, với họa tiết hoạt hình thú vị, giúp người mặc mang lại cảm giác tươi trẻ.',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '230000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '6',    
                'km_id'             => NULL,    
                'kho_id'            => '2',    
            ],
            [
                'sp_id'             => '21',
                'sp_ten'            => 'ÁO SƠ MI G2',
                  
                //'sp_hinh'           => 'somiG1_trang.jpg',    
                //'sp_soluong'        => '0',    
                'sp_mota'           => 'Áo sơ mi G2, với họa tiết hoạt hình thú vị, giúp người mặc mang lại cảm giác tươi trẻ.',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '230000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '6',    
                'km_id'             => NULL,    
                'kho_id'            => '2',    
            ],
            [
                'sp_id'             => '22',
                'sp_ten'            => 'ÁO SƠ MI G3',
                  
               // 'sp_hinh'           => 'somiG3_den.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Áo sơ mi G3, với họa tiết caro cổ điển, đem lại cảm giác lịch sự và tươi trẻ cho người mặc.',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '230000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '6',    
                'km_id'             => NULL,    
                'kho_id'            => '2',    
            ],
            [
                'sp_id'             => '23',
                'sp_ten'            => 'ÁO SƠ MI G4',
                   
                //'sp_hinh'           => 'somiG4_xanh.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Áo sơ mi G4, với họa tiết caro cổ điển, đem lại cảm giác lịch sự và tươi trẻ cho người mặc.',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '230000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '6',    
                'km_id'             => '3',    
                'kho_id'            => '2',    
            ],
            [
                'sp_id'             => '24',
                'sp_ten'            => 'ÁO SƠ MI G5',
                    
               // 'sp_hinh'           => 'somiG5_den.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Áo sơ mi G5, với gam màu trơn cổ điển, đem lại cảm giác lịch sự và tươi trẻ cho người mặc.',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '220000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '6',    
                'km_id'             => NULL,    
                'kho_id'            => '2',    
            ],
            [
                'sp_id'             => '25',
                'sp_ten'            => 'QUẦN SHORT G1',
                   
                //'sp_hinh'           => 'quanshortG1_xanh.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Quần short G1 dành cho các bạn nữ xì tin, thích hợp khi phối cùng với những chiếc áo thun đơn giản, mang lại cảm giác năng động cho người mặc. ',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '300000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '7',    
                'km_id'             => NULL,    
                'kho_id'            => '2',    
            ],
            [
                'sp_id'             => '26',
                'sp_ten'            => 'QUẦN SHORT G2',
                  
                //'sp_hinh'           => 'quanshortG2_xanh.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Quần short G2 dành cho các bạn nữ xì tin, thích hợp khi phối cùng với những chiếc áo thun đơn giản, mang lại cảm giác năng động cho người mặc. ',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '300000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '7',    
                'km_id'             => NULL,    
                'kho_id'            => '2',    
            ],
            [
                'sp_id'             => '27',
                'sp_ten'            => 'QUẦN SHORT G3',
                    
               // 'sp_hinh'           => 'quanshortG3_den.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Quần short G3 dành cho các bạn nữ xì tin, thích hợp khi phối cùng với những chiếc áo thun đơn giản, mang lại cảm giác năng động cho người mặc. ',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '300000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '7',    
                'km_id'             => '2',    
                'kho_id'            => '2',    
            ],
            [
                'sp_id'             => '28',
                'sp_ten'            => 'QUẦN SHORT G4',
                   
                //'sp_hinh'           => 'quanshortG4_trang.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Quần short G4 dành cho các bạn nữ xì tin, thích hợp khi phối cùng với những chiếc áo thun đơn giản, mang lại cảm giác năng động cho người mặc. ',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '300000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '7',    
                'km_id'             => NULL,    
                'kho_id'            => '2',    
            ],
            [
                'sp_id'             => '29',
                'sp_ten'            => 'QUẦN SHORT G5',
                  
               // 'sp_hinh'           => 'quanshortG5_xanh.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Quần short G5 dành cho các bạn nữ xì tin, thích hợp khi phối cùng với những chiếc áo thun đơn giản, mang lại cảm giác năng động cho người mặc. ',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '300000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '7',    
                'km_id'             => NULL,    
                'kho_id'            => '2',    
            ],
            [
                'sp_id'             => '30',
                'sp_ten'            => 'QUẦN JEAN G1',
                   
               // 'sp_hinh'           => 'quanjeanG1_den.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Quần jean G1 dành cho các bạn nữ xì tin, thích hợp khi phối cùng với những chiếc áo kiểu đơn giản, mang lại cảm giác năng động cho người mặc. ',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '350000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '8',    
                'km_id'             => '2',    
                'kho_id'            => '2',    
            ],
            [
                'sp_id'             => '31',
                'sp_ten'            => 'QUẦN JEAN G2',
                  
               // 'sp_hinh'           => 'quanjeanG2_trang.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Quần jean G2 dành cho các bạn nữ xì tin, thích hợp khi phối cùng với những chiếc áo kiểu đơn giản, mang lại cảm giác năng động cho người mặc. ',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '350000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '8',    
                'km_id'             => NULL,    
                'kho_id'            => '2',    
            ],
            [
                'sp_id'             => '32',
                'sp_ten'            => 'QUẦN JEAN G3',
                    
                //'sp_hinh'           => 'quanjeanG3_den.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Quần jean G3 dành cho các bạn nữ xì tin, thích hợp khi phối cùng với những chiếc áo kiểu đơn giản, mang lại cảm giác năng động cho người mặc. ',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '350000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '8',    
                'km_id'             => NULL,    
                'kho_id'            => '2',    
            ],
            [
                'sp_id'             => '33',
                'sp_ten'            => 'QUẦN JEAN G4',
                  
               // 'sp_hinh'           => 'quanjeanG4_xanh.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Quần jean G4 dành cho các bạn nữ xì tin, thích hợp khi phối cùng với những chiếc áo kiểu đơn giản, mang lại cảm giác năng động cho người mặc. ',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '350000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '8',    
                'km_id'             => NULL,    
                'kho_id'            => '2',    
            ],
            [
                'sp_id'             => '34',
                'sp_ten'            => 'ÁO THUN ĐÔI C1',
                   
               // 'sp_hinh'           => 'thundoiC1_trang.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Áo thun đôi C1 chất liệu cotton mềm mịn, với gam màu đơn tươi sáng, kèm logo đơn giản, giúp các cặp đôi trẻ trung, năng động khi cùng nhau diện xuống phố.',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '250000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '9',    
                'km_id'             => NULL,    
                'kho_id'            => '3',    
            ],
            [
                'sp_id'             => '35',
                'sp_ten'            => 'ÁO THUN ĐÔI C2',
                   
               // 'sp_hinh'           => 'thundoiC2_den.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Áo thun đôi C2 chất liệu cotton mềm mịn, với gam màu đơn tươi sáng, kèm logo đơn giản, giúp các cặp đôi trẻ trung, năng động khi cùng nhau diện xuống phố.',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '250000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '9',    
                'km_id'             => NULL,    
                'kho_id'            => '3',    
            ],
            [
                'sp_id'             => '36',
                'sp_ten'            => 'ÁO THUN ĐÔI C3',
                   
                //'sp_hinh'           => 'thundoiC3_xanh.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Áo thun đôi C3 chất liệu cotton mềm mịn, với gam màu đơn tươi sáng, kèm logo đơn giản, giúp các cặp đôi trẻ trung, năng động khi cùng nhau diện xuống phố.',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',    
                'sp_giaban'         => '250000',        
                'sp_trangthai'      => '1',        
                 'lsp_id'            => '9',    
                'km_id'             => NULL,    
                'kho_id'            => '3',    
            ],
           
            [
                'sp_id'             => '37',
                'sp_ten'            => 'ÁO THUN ĐÔI C4',
                  
                //'sp_hinh'           => 'thundoiC4_den.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Áo thun đôi C4 chất liệu cotton mềm mịn, với gam màu đơn tươi sáng, kèm logo đơn giản, giúp các cặp đôi trẻ trung, năng động khi cùng nhau diện xuống phố.',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '280000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '9',    
                'km_id'             => NULL,    
                'kho_id'            => '3',    
            ],
            [
                'sp_id'             => '38',
                'sp_ten'            => 'ÁO THUN ĐÔI C5',
                  
               // 'sp_hinh'           => 'thundoiC5_xanh.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Áo thun đôi C5 chất liệu cotton mềm mịn, với gam màu đơn tươi sáng, kèm logo đơn giản, giúp các cặp đôi trẻ trung, năng động khi cùng nhau diện xuống phố.',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '280000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '9',    
                'km_id'             => NULL,    
                'kho_id'            => '3',    
            ],
            [
                'sp_id'             => '39',
                'sp_ten'            => 'ÁO KHOÁC ĐÔI C1',
                   
               // 'sp_hinh'           => 'khoacdoiC1_den.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Áo khoác đôi C1 với gam màu đơn tươi sáng, kèm logo đơn giản, giúp các cặp đôi trẻ trung, năng động khi cùng nhau diện xuống phố.',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '500000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '10',    
                'km_id'             => '3',    
                'kho_id'            => '3',    
            ],
            [
                'sp_id'             => '40',
                'sp_ten'            => 'ÁO KHOÁC ĐÔI C2',
                 
               // 'sp_hinh'           => 'khoacdoiC2_xanh.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Áo khoác đôi C2 với gam màu đơn tươi sáng, kèm logo đơn giản, giúp các cặp đôi trẻ trung, năng động khi cùng nhau diện xuống phố.',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '600000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '10',    
                'km_id'             => NULL,    
                'kho_id'            => '3',    
            ],
            [
                'sp_id'             => '41',
                'sp_ten'            => 'ÁO KHOÁC ĐÔI C3',
                  
               // 'sp_hinh'           => 'khoacdoiC3_xanh.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Áo khoác đôi C3 với gam màu đơn tươi sáng, kèm logo đơn giản, giúp các cặp đôi trẻ trung, năng động khi cùng nhau diện xuống phố.',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '600000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '10',    
                'km_id'             => NULL,    
                'kho_id'            => '3',    
            ],
            [
                'sp_id'             => '42',
                'sp_ten'            => 'ÁO KHOÁC ĐÔI C4',
                   
                //'sp_hinh'           => 'khoacdoiC4_xanh.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Áo khoác đôi C4 với gam màu đơn tươi sáng, kèm logo đơn giản, giúp các cặp đôi trẻ trung, năng động khi cùng nhau diện xuống phố.',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',
                'sp_giaban'         => '600000',    
                'sp_trangthai'      => '1',    
                'lsp_id'            => '10',    
                'km_id'             => NULL,    
                'kho_id'            => '3',    
            ],
            [
                'sp_id'             => '43',
                'sp_ten'            => 'ÁO KHOÁC ĐÔI C5',
                  
               // 'sp_hinh'           => 'khoacdoiC5_xanh.jpg',    
               // 'sp_soluong'        => '0',    
                'sp_mota'           => 'Áo khoác đôi C5 với gam màu đơn trông tươi trẻ và cá tính, giúp các cặp đôi trẻ trung, năng động khi cùng nhau diện xuống phố.',    
                // 'sp_ngaytaomoi'     => '2020-10-06',    
                // 'sp_ngaycapnhat'    => '2020-10-06',    
                'sp_giaban'         => '800000', 
                'sp_trangthai'      => '1',    
                'lsp_id'            => '10',    
                'km_id'             => '3',    
                'kho_id'            => '3',    
            ],
        ];
        DB::table('sanpham')->insert($list);
    }
}
